<a href="https://colab.research.google.com/github/yousefahmed2004/ANN_TANH/blob/main/backbrogration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
import numpy as np

input_size = 2
hidden_size = 2
num_classes = 2
learning_rate = 0.1

Neuron_1 = 0.05
Neuron_2 = 0.1

Weight_input_hidden = np.random.uniform(0.0, 0.1, (hidden_size, input_size))
Weight_input_hidden = np.round(Weight_input_hidden, 3)
Weight_hidden_output = np.random.uniform(0.0, 0.1, (num_classes, hidden_size))
Weight_hidden_output = np.round(Weight_hidden_output, 3)

bias_1 = np.array([0.5, 0.5])
bias_2 = np.array([0.7, 0.7])

print(Weight_input_hidden)
print(Weight_hidden_output)

def net(inputs, weights, bias):
    net = np.dot(weights, inputs) - bias
    return net

def activation(net):
    return 2 / (1 + np.exp(-2 * net)) - 1

inputs = np.array([Neuron_1, Neuron_2])
hidden_net = net(inputs, Weight_input_hidden, bias_1)
hidden_outputs = activation(hidden_net)
print("Hidden layer outputs:", hidden_outputs)

output_net = net(hidden_outputs, Weight_hidden_output, bias_2)
outputs = activation(output_net)
print("Output layer outputs:", outputs)

target_output = np.array([0.01, 0.99])
error_output = target_output - outputs
derivative_output = 1 - outputs**2
delta_output = error_output * derivative_output
gradient_hidden_output = np.outer(delta_output, hidden_outputs)

derivative_hidden = 1 - hidden_outputs**2
delta_hidden = np.dot(Weight_hidden_output.T, delta_output) * derivative_hidden
gradient_input_hidden = np.outer(delta_hidden, inputs)

Weight_hidden_output += learning_rate * gradient_hidden_output
Weight_hidden_output = np.round(Weight_hidden_output, 4)
Weight_input_hidden += learning_rate * gradient_input_hidden
Weight_input_hidden = np.round(Weight_input_hidden, 4)

print("Updated Weight_input_hidden:\n", Weight_input_hidden)
print("Updated Weight_hidden_output:\n", Weight_hidden_output)

[[0.09  0.082]
 [0.053 0.041]]
[[0.064 0.033]
 [0.076 0.05 ]]
Hidden layer outputs: [-0.45207085 -0.45679211]
Output layer outputs: [-0.6315598  -0.63942296]
Updated Weight_input_hidden:
 [[0.0904 0.0828]
 [0.0532 0.0415]]
Updated Weight_hidden_output:
 [[0.0466 0.0154]
 [0.0325 0.006 ]]
